### ISSUE TITLE
TSEBRA failed with keep_ab_initio.cfg (but worked with default.cfg)

### ISSUE THREAD

**Issue by Huiting120** [Gaius-Augustus/TSEBRA#28]
Hi, 
I was running TSEBRA with both the default.cfg and keep_ab_initio.cfg. The first run with the default.cfg was successful, however, the run the keep_ab_initio.cfg failed with the following error:
`$ ../TSEBRA/bin/tsebra.py -g braker1_augustus.hints.gtf,braker2_augustus.hints.gtf -e braker1_hintsfile.gff,braker2_hintsfile.gff -c keep_ab_initio.cfg -o braker.combined.gtf
### SELECT TRANSCRIPTS
Traceback (most recent call last):
  File "/home/tech/Documents/TSEBRA/keep_ab_initio/../TSEBRA/bin/tsebra.py", line 228, in <module>
    main()
  File "/home/tech/Documents/TSEBRA/keep_ab_initio/../TSEBRA/bin/tsebra.py", line 105, in main
    combined_prediction = graph.get_decided_graph()
  File "/home/tech/Documents/TSEBRA/TSEBRA/bin/overlap_graph.py", line 433, in get_decided_graph
    self.decide_graph()
  File "/home/tech/Documents/TSEBRA/TSEBRA/bin/overlap_graph.py", line 408, in decide_graph
    self.edges[key].node_to_remove = self.decide_edge(self.edges[key])
  File "/home/tech/Documents/TSEBRA/TSEBRA/bin/overlap_graph.py", line 346, in decide_edge
    if diff > self.para[f'e_{i+1}']:
KeyError: 'e_5'`

The default.cfg has e_5 and e_6, but the keep_ab_initio.cfg does not. But I've ran other annotations without e_5 and e_6 pre-set in the configuration file before and this error did not occur. I wonder what caused the error this time. Any insights would be helpful.

Thanks in advance.

**Comment by Huiting120** [comment]
I see the scripts and default.cfg was updated last week. Does the new script require e_5 and e_6? If so, can you provide an updated keep_ab_initio.cfg please? 
Thanks
