### ISSUE TITLE
long_reads branch issue

### ISSUE THREAD

**Issue by gbdias** [Gaius-Augustus/TSEBRA#36]
Hi,

I tried running tsebra using the *long_reads* branch but I'm getting this error. 

```
### BUILD OVERLAP GRAPH
Traceback (most recent call last):
  File "/home/guibo205/git/TSEBRA/bin/tsebra.py", line 224, in <module>
    main()
  File "/home/guibo205/git/TSEBRA/bin/tsebra.py", line 106, in main
    graph.build()
  File "/home/guibo205/git/TSEBRA/bin/overlap_graph.py", line 182, in build
    open_intervals.remove(interval[0])
ValueError: list.remove(x): x not in list
```

This is my command:
```
"$TSEBRA" -g "$BRAKER_PREDS","$GALBA_PREDS" -e "$BRAKER_HINTS","$GALBA_HINTS" \
 -l "$ISOSEQ_PREDS" -c long_reads.cfg -f -o tsebra_rm_short.gtf
```

Any tips appreciated.

**Comment by AnnikaMueller05** [comment]
Hi, @KatharinaHoff has previously suggested using the container as described here: https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/posters/poster_PAG2024.pdf 
I don't know whether that will solve the error, but it's worth a try
