### ISSUE TITLE
Execution issue still persists with ```get_longest_isoform.py```

### ISSUE THREAD

**Issue by sahoo-rk** [Gaius-Augustus/TSEBRA#49]
I execute the script with a single ```braker.gtf``` file and the error still persists in the updated version.

```
get_longest_isoform.py --gtf braker.gtf --out longiso.gtf

### READING GENE PREDICTION: [braker.gtf]
### BUILD OVERLAP GRAPH
### CHOOSE LONGEST ISOFORM FOR EACH GENE
Traceback (most recent call last):
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 107, in <module>
    main()
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 63, in main
    tx_longest = sorted([graph.__tx_from_key__(n) for \
  File "/home/sahoork/dumpack/TSEBRA/bin/get_longest_isoform.py", line 64, in <lambda>
    n in comp], key=lambda t:t.get_cds_len())[-1]
AttributeError: 'Transcript' object has no attribute 'get_cds_len'
```
I have gone through the issue at #34 ; and am currently using the updated release. 
Am I missing something here? Please suggest.

Thanks,

**Comment by LarsGab** [comment]
Hi, 

I made an update that should fix this issue.

Best,
Lars
